name: Export Conda Packages List

on:
  workflow_dispatch:

jobs:
  export-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files in working directory (debug)
        run: ls -l

      - name: Export packages list to file
        run: |
          yq e '.package[] | .name + " " + .version' default.conda-lock.yml > packages.txt

      - name: Upload packages.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages-list
          path: packages.txt
